export const dataType  = {
    SET_SEARCH_BY_SYMBOL: "SET_SEARCH_BY_SYMBOL",
    SET_LAST_STATUS_DEPTH_RESP: "SET_LAST_STATUS_DEPTH_RESP",
    SET_DEPTH_DATA: "SET_DEPTH_DATA",
    SET_STREAM_DATA: "SET_STREAM_DATA",
    SET_DECIMAL_GROUP_BY: "SET_DECIMAL_GROUP_BY",
    SET_DEPTH_VIEW_COUNT: "SET_DEPTH_VIEW_COUNT",
};